apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::492390865085:role/secrets-manager-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager-sa
  namespace: staging
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::492390865085:role/secrets-manager-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager-sa
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::492390865085:role/secrets-manager-role
