apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: staging
  labels:
    app: backend-app
    environment: staging
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend-app
